POST http://localhost:3001/api/games/order
Content-Type: application/json 

{
    "creditCardName" : "JOHN",
    "orderDetails" : [ {
    "_id": "63fb4cd9230ff245bd87d3aa",
    "title": "One Piece Odyssey",
    "description": "Sakuraba",
    "frontImage": "https://res.cloudinary.com/dabvgy03h/image/upload/v1677412555/games%20shop/onepeace_uqro5z.png",
    "price": 49,
    "img1": "https://images.g2a.com/uiadminimages/770x433/1x1x1/1c85bab1c9c1/13f74bf2d28f49009298e34b",
    "img2": "https://images.g2a.com/uiadminimages/770x433/1x1x1/2055146986d8/06826dab375a47b3bf6e258b",
    "rating": 8,
    "iframe": "https://www.youtube.com/embed/LPqxnPVdDX8",
    "platform": "PS4",
    "cartQuantity" : 1
  }] 
 
}

###
DELETE http://localhost:3001/api/games/deleteOrder/6462059b968a3314bac4b0a8
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZjYyYjlmZmNhOWE4NTcxNWM1NmUwNiIsImlhdCI6MTY4NDE1MjUyMiwiZXhwIjoxNjg0MjM4OTIyfQ.DvcP4AWGv_8XMPs2C21u0UjR6ooct95WRTlTXWTPuyk

###
GET http://localhost:3001/api/games/cart/lishayst100

####
PUT http://localhost:3001/api/games/updateStatus/646606c8567f4c4992d48090
Content-Type: application/json 
